# ===================================
#  Relation Behavior Config
# ===================================

daftarPertanyaan:
    label: Membuat Pertanyaan
    view:
        list: $/yfktn/surveykepuasan/models/pertanyaansurvey/columns-disurvey.yaml
        toolbarButtons: create|delete
            # create: Tambahkan Pertanyaan Survey
            # delete: Hapus Pertanyaan Survey
    manage:
        form: $/yfktn/surveykepuasan/models/pertanyaansurvey/fields.yaml
        recordsPerPage: 10
    customMessages:
        buttonCreate: Tambahkan Pertanyaan Survey
        buttonDelete: Hapus Pertanyaan Survey
daftarJawaban:
    label: Daftar Jawaban
    readOnly: true
    view:
        list: $/yfktn/surveykepuasan/models/jawabansurvey/columns.yaml
        recordsPerPage: 20
